export const GET_SELECTABLE_TEMPLATES = 'GET_SELECTABLE_TEMPLATES';
export const TOGGLE_SHOW_TEMPLATES_MODAL = 'TOGGLE_SHOW_TEMPLATES_MODAL';
export const TOGGLE_THUMBNAIL_CREATION = 'TOGGLE_THUMBNAIL_CREATION';

export const GET_TEMPLATE_CONTAINERS = 'GET_TEMPLATE_CONTAINERS';
